function tvRP.getNearestVehicles(radius)
	local r = {}

	local vehs = {}
	local it,veh = FindFirstVehicle()
	if veh then
		vehs[#vehs + 1] = veh
	end
	local ok
	repeat
		ok,veh = FindNextVehicle(it)
		if ok and veh then
			vehs[#vehs + 1] = veh
		end
	until not ok
	EndFindVehicle(it)

	for _,veh in pairs(vehs) do
		local distance = #(GetEntityCoords(veh) - GetEntityCoords(PlayerPedId()))
		if distance <= radius then
			r[veh] = distance
		end
	end
	return r
end

function tvRP.getNearestVehicle(radius)
	local veh
	local vehs = tvRP.getNearestVehicles(radius)
	local min = radius+0.0001
	for _veh,dist in pairs(vehs) do
		if dist < min then
			min = dist
			veh = _veh
		end
	end
	return veh 
end

function tvRP.ejectVehicle()
	local ped = PlayerPedId()
	if IsPedSittingInAnyVehicle(ped) then
		TaskLeaveVehicle(ped,GetVehiclePedIsIn(ped),4160)
	end
end

function tvRP.isInVehicle()
	return IsPedSittingInAnyVehicle(PlayerPedId())
end
-----------------------------------------------------------------------------------------------------------------------------------------
-- VEHLIST
-----------------------------------------------------------------------------------------------------------------------------------------
local vehList = {
	-- CARROS NOVOS TUNERS
	{ ['name'] = "sultan3", ['banned'] = false },
	{ ['name'] = "cypher", ['banned'] = false },
	{ ['name'] = "jester4", ['banned'] = false },
	{ ['name'] = "comet6", ['banned'] = false },
	{ ['name'] = "growler", ['banned'] = false },

	{ ['name'] = "bmwm3e36", ['banned'] = false },
	{ ['name'] = "toyotasupra", ['banned'] = false },
	{ ['name'] = "ferrarif12", ['banned'] = false },

	{ ['name'] = "vectre", ['banned'] = false },
	{ ['name'] = "zr350", ['banned'] = false },
	{ ['name'] = "calico", ['banned'] = false },
	{ ['name'] = "euros", ['banned'] = false },
	{ ['name'] = "rt3000", ['banned'] = false },

    -- CARROS ATT
	{ ['name'] = "sultan2", ['banned'] = false },
	{ ['name'] = "jugular", ['banned'] = false },
	{ ['name'] = "kanjo", ['banned'] = false },
	{ ['name'] = "asbo", ['banned'] = false },
	{ ['name'] = "club", ['banned'] = false },
	{ ['name'] = "brioso2", ['banned'] = false },
	{ ['name'] = "weevil", ['banned'] = false },
	{ ['name'] = "rrocket", ['banned'] = false },
	{ ['name'] = "stryder", ['banned'] = false },
	{ ['name'] = "manchez2", ['banned'] = false },
	{ ['name'] = "dukes3", ['banned'] = false },
	{ ['name'] = "gauntlet3", ['banned'] = false },
	{ ['name'] = "gauntlet4", ['banned'] = false },
	{ ['name'] = "gauntlet5", ['banned'] = false },
	{ ['name'] = "peyote2", ['banned'] = false },
	{ ['name'] = "yosemite2", ['banned'] = false },
	{ ['name'] = "yosemite3", ['banned'] = false },
	{ ['name'] = "caracara2", ['banned'] = false },
	{ ['name'] = "everon", ['banned'] = false },
	{ ['name'] = "hellion", ['banned'] = false },
	{ ['name'] = "outlaw", ['banned'] = false },
	{ ['name'] = "vagrant", ['banned'] = false },
	{ ['name'] = "zhaba", ['banned'] = false },
	{ ['name'] = "verus", ['banned'] = false },
	{ ['name'] = "winky", ['banned'] = false },
	{ ['name'] = "formula", ['banned'] = false },
	{ ['name'] = "formula2", ['banned'] = false },
	{ ['name'] = "openwheel1", ['banned'] = false },
	{ ['name'] = "openwheel2", ['banned'] = false },
	{ ['name'] = "landstalker2", ['banned'] = false },
	{ ['name'] = "novak", ['banned'] = false },
	{ ['name'] = "rebla", ['banned'] = false },
	{ ['name'] = "seminole2", ['banned'] = false },
	{ ['name'] = "squaddie", ['banned'] = false },
	{ ['name'] = "glendale2", ['banned'] = false },
	{ ['name'] = "coquette4", ['banned'] = false },
	{ ['name'] = "drafter", ['banned'] = false },
	{ ['name'] = "komoda", ['banned'] = false },
	{ ['name'] = "imorgon", ['banned'] = false },
	{ ['name'] = "issi7", ['banned'] = false },
	{ ['name'] = "locust", ['banned'] = false },
	{ ['name'] = "neo", ['banned'] = false },
	{ ['name'] = "paragon", ['banned'] = false },
	{ ['name'] = "penumbra2", ['banned'] = false },
	{ ['name'] = "sugoi", ['banned'] = false },
	{ ['name'] = "vstr", ['banned'] = false },
	{ ['name'] = "veto", ['banned'] = false },
	{ ['name'] = "veto2", ['banned'] = false },
	{ ['name'] = "dynasty", ['banned'] = false },
	{ ['name'] = "peyote3", ['banned'] = false },
	{ ['name'] = "retinue2", ['banned'] = false },
	{ ['name'] = "nebula", ['banned'] = false },
	{ ['name'] = "zion3", ['banned'] = false },
	{ ['name'] = "emerus", ['banned'] = false },
	{ ['name'] = "furia", ['banned'] = false },
	{ ['name'] = "krieger", ['banned'] = false },
	{ ['name'] = "s80", ['banned'] = false },
	{ ['name'] = "thrax", ['banned'] = false },
	{ ['name'] = "tigon", ['banned'] = false },
	{ ['name'] = "zorrusso", ['banned'] = false },
	{ ['name'] = "slamtruck", ['banned'] = false },
	{ ['name'] = "youga3", ['banned'] = false },

	-- VIPS MOTOS
	{ ['name'] = "f800", ['banned'] = false },
	{ ['name'] = "gs1200", ['banned'] = false },
	{ ['name'] = "tiger", ['banned'] = false },
	{ ['name'] = "africat", ['banned'] = false },
	{ ['name'] = "cbr1000rrr", ['banned'] = false },
	{ ['name'] = "h2carb", ['banned'] = false },
	{ ['name'] = "pcx", ['banned'] = false },
	{ ['name'] = "xt700", ['banned'] = false },
	{ ['name'] = "r1", ['banned'] = false },
	{ ['name'] = "r6", ['banned'] = false },
	{ ['name'] = "cb500x", ['banned'] = false },
	{ ['name'] = "xadv", ['banned'] = false },

	-- VIPS
	{ ['name'] = "xnsgt", ['banned'] = false },
	{ ['name'] = "bmci", ['banned'] = false },
	{ ['name'] = "bmwm4gts", ['banned'] = false },
	{ ['name'] = "audirs7", ['banned'] = false },
	{ ['name'] = "porschestart", ['banned'] = false },

	{ ['name'] = "bmwi8", ['banned'] = false },
	{ ['name'] = "ferrariitalia", ['banned'] = false },
	{ ['name'] = "765lt", ['banned'] = false },
	{ ['name'] = "lamborghinihuracan", ['banned'] = false },
	{ ['name'] = "nissangtr", ['banned'] = false },
	{ ['name'] = "lancerevolutionx", ['banned'] = false },
	{ ['name'] = "mazdarx7", ['banned'] = false },
	{ ['name'] = "nissangtrnismo", ['banned'] = false },
	{ ['name'] = "nissanskyliner34", ['banned'] = false },
	{ ['name'] = "skyline", ['banned'] = false },
	{ ['name'] = "nissanskylinerocket", ['banned'] = false },
	{ ['name'] = "rmodx6", ['banned'] = false },
	{ ['name'] = "gt2rsmr", ['banned'] = false },
	{ ['name'] = "teslaprior", ['banned'] = false },
	{ ['name'] = "mlnovitec", ['banned'] = false },
	{ ['name'] = "brz13", ['banned'] = false },
	{ ['name'] = "golfgti7", ['banned'] = false },
	{ ['name'] = "pturismo", ['banned'] = false },
	{ ['name'] = "pcs18", ['banned'] = false },
	{ ['name'] = "ben17", ['banned'] = false },
	{ ['name'] = "amarok", ['banned'] = false },
	{ ['name'] = "bmwm8", ['banned'] = false },
	{ ['name'] = "lancerevolution9", ['banned'] = false },
	{ ['name'] = "urus", ['banned'] = false },
	{ ['name'] = "f8t", ['banned'] = false },
	{ ['name'] = "r820", ['banned'] = false },
	{ ['name'] = "amggt63s", ['banned'] = false },
	{ ['name'] = "mercedesgt63", ['banned'] = false },
	--Att dia 28/11/2021
	{ ['name'] = "lp610", ['banned'] = false },
	{ ['name'] = "pts21", ['banned'] = false },
	{ ['name'] = "rs62", ['banned'] = false },
	{ ['name'] = "19gt500", ['banned'] = false },
	{ ['name'] = "745le", ['banned'] = false },
	{ ['name'] = "22g63", ['banned'] = true },
	{ ['name'] = "jettagli", ['banned'] = true },
	{ ['name'] = "xj6", ['banned'] = true },
	{ ['name'] = "l200", ['banned'] = true },
	{ ['name'] = "gxa45", ['banned'] = true },
	{ ['name'] = "ocnetrongt", ['banned'] = true },
	{ ['name'] = "contgt20c", ['banned'] = true },
	-- POLICIA SUL
	{ ['name'] = "wrcontender", ['banned'] = true },
	{ ['name'] = "wrdouble", ['banned'] = true },
	{ ['name'] = "wrgranger", ['banned'] = true },
	{ ['name'] = "wrgrowler", ['banned'] = true },
	{ ['name'] = "wrkomoda", ['banned'] = true },
	{ ['name'] = "wrtrx", ['banned'] = true },
	-- PARAMEDICO
	{ ['name'] = "emstalker", ['banned'] = true },
	{ ['name'] = "ambulance", ['banned'] = true },
	{ ['name'] = "palmav", ['banned'] = true },
	-- CARROS NORMAIS
	{ ['name'] = "futo", ['banned'] = false },
	{ ['name'] = "jester", ['banned'] = false },
	{ ['name'] = "kuruma", ['banned'] = false },
	{ ['name'] = "blista", ['banned'] = false },
	{ ['name'] = "brioso", ['banned'] = false },
	{ ['name'] = "dilettante", ['banned'] = false },
	{ ['name'] = "issi2", ['banned'] = false },
	{ ['name'] = "panto", ['banned'] = false },
	{ ['name'] = "prairie", ['banned'] = false },
	{ ['name'] = "rhapsody", ['banned'] = false },
	{ ['name'] = "cogcabrio", ['banned'] = false },
	{ ['name'] = "emperor", ['banned'] = false },
	{ ['name'] = "emperor2", ['banned'] = false },
	{ ['name'] = "phoenix", ['banned'] = false },
	{ ['name'] = "premier", ['banned'] = false },
	{ ['name'] = "glendale", ['banned'] = false },
	{ ['name'] = "intruder", ['banned'] = false },
	{ ['name'] = "exemplar", ['banned'] = false },
	{ ['name'] = "f620", ['banned'] = false },
	{ ['name'] = "felon", ['banned'] = false },
	{ ['name'] = "ingot", ['banned'] = false },
	{ ['name'] = "felon2", ['banned'] = false },
	{ ['name'] = "jackal", ['banned'] = false },
	{ ['name'] = "oracle", ['banned'] = false },
	{ ['name'] = "oracle2", ['banned'] = false },
	{ ['name'] = "sentinel", ['banned'] = false },
	{ ['name'] = "sentinel2", ['banned'] = false },
	{ ['name'] = "windsor", ['banned'] = false },
	{ ['name'] = "windsor2", ['banned'] = false },
	{ ['name'] = "zion", ['banned'] = false },
	{ ['name'] = "zion2", ['banned'] = false },
	{ ['name'] = "blade", ['banned'] = false },
	{ ['name'] = "buccaneer", ['banned'] = false },
	{ ['name'] = "buccaneer2", ['banned'] = false },
	{ ['name'] = "primo", ['banned'] = false },
	{ ['name'] = "primo2", ['banned'] = false },
	{ ['name'] = "chino", ['banned'] = false },
	{ ['name'] = "chino2", ['banned'] = false },
	{ ['name'] = "coquette3", ['banned'] = false },
	{ ['name'] = "dominator", ['banned'] = false },
	{ ['name'] = "dominator2", ['banned'] = false },
	{ ['name'] = "dukes", ['banned'] = false },
	{ ['name'] = "faction", ['banned'] = false },
	{ ['name'] = "faction2", ['banned'] = false },
	{ ['name'] = "faction3", ['banned'] = false },
	{ ['name'] = "gauntlet", ['banned'] = false },
	{ ['name'] = "gauntlet2", ['banned'] = false },
	{ ['name'] = "hermes", ['banned'] = false },
	{ ['name'] = "hotknife", ['banned'] = false },
	{ ['name'] = "moonbeam", ['banned'] = false },
	{ ['name'] = "moonbeam2", ['banned'] = false },
	{ ['name'] = "nightshade", ['banned'] = false },
	{ ['name'] = "picador", ['banned'] = false },
	{ ['name'] = "ruiner", ['banned'] = false },
	{ ['name'] = "sabregt", ['banned'] = false },
	{ ['name'] = "sabregt2", ['banned'] = false },
	{ ['name'] = "gburrito", ['banned'] = false },
	{ ['name'] = "slamvan", ['banned'] = false },
	{ ['name'] = "slamvan2", ['banned'] = false },
	{ ['name'] = "slamvan3", ['banned'] = false },
	{ ['name'] = "stalion", ['banned'] = false },
	{ ['name'] = "stalion2", ['banned'] = false },
	{ ['name'] = "tampa", ['banned'] = false },
	{ ['name'] = "vigero", ['banned'] = false },
	{ ['name'] = "virgo", ['banned'] = false },
	{ ['name'] = "virgo2", ['banned'] = false },
	{ ['name'] = "virgo3", ['banned'] = false },
	{ ['name'] = "voodoo", ['banned'] = false },
	{ ['name'] = "voodoo2", ['banned'] = false },
	{ ['name'] = "yosemite", ['banned'] = false },
	{ ['name'] = "bfinjection", ['banned'] = false },
	{ ['name'] = "bifta", ['banned'] = false },
	{ ['name'] = "bodhi2", ['banned'] = false },
	{ ['name'] = "brawler", ['banned'] = false },
	{ ['name'] = "trophytruck", ['banned'] = false },
	{ ['name'] = "trophytruck2", ['banned'] = false },
	{ ['name'] = "dubsta3", ['banned'] = false },
	{ ['name'] = "mesa3", ['banned'] = false },
	{ ['name'] = "rancherxl", ['banned'] = false },
	{ ['name'] = "rebel", ['banned'] = false },
	{ ['name'] = "rebel2", ['banned'] = false },
	{ ['name'] = "riata", ['banned'] = false },
	{ ['name'] = "dloader", ['banned'] = false },
	{ ['name'] = "ratloader", ['banned'] = false },
	{ ['name'] = "sandking", ['banned'] = false },
	{ ['name'] = "sandking2", ['banned'] = false },
	{ ['name'] = "baller", ['banned'] = false },
	{ ['name'] = "baller2", ['banned'] = false },
	{ ['name'] = "baller3", ['banned'] = false },
	{ ['name'] = "baller4", ['banned'] = false },
	{ ['name'] = "baller5", ['banned'] = false },
	{ ['name'] = "baller6", ['banned'] = false },
	{ ['name'] = "bjxl", ['banned'] = false },
	{ ['name'] = "cavalcade", ['banned'] = false },
	{ ['name'] = "cavalcade2", ['banned'] = false },
	{ ['name'] = "contender", ['banned'] = false },
	{ ['name'] = "dubsta", ['banned'] = false },
	{ ['name'] = "dubsta2", ['banned'] = false },
	{ ['name'] = "fq2", ['banned'] = false },
	{ ['name'] = "granger", ['banned'] = false },
	{ ['name'] = "gresley", ['banned'] = false },
	{ ['name'] = "habanero", ['banned'] = false },
	{ ['name'] = "seminole", ['banned'] = false },
	{ ['name'] = "serrano", ['banned'] = false },
	{ ['name'] = "xls", ['banned'] = false },
	{ ['name'] = "xls2", ['banned'] = false },
	{ ['name'] = "asea", ['banned'] = false },
	{ ['name'] = "asterope", ['banned'] = false },
	{ ['name'] = "cog55", ['banned'] = false },
	{ ['name'] = "cog552", ['banned'] = false },
	{ ['name'] = "cognoscenti", ['banned'] = false },
	{ ['name'] = "cognoscenti2", ['banned'] = false },
	{ ['name'] = "stanier", ['banned'] = false },
	{ ['name'] = "stratum", ['banned'] = false },
	{ ['name'] = "superd", ['banned'] = false },
	{ ['name'] = "surge", ['banned'] = false },
	{ ['name'] = "tailgater", ['banned'] = false },
	{ ['name'] = "warrener", ['banned'] = false },
	{ ['name'] = "washington", ['banned'] = false },
	{ ['name'] = "alpha", ['banned'] = false },
	{ ['name'] = "banshee", ['banned'] = false },
	{ ['name'] = "bestiagts", ['banned'] = false },
	{ ['name'] = "blista2", ['banned'] = false },
	{ ['name'] = "blista3", ['banned'] = false },
	{ ['name'] = "buffalo", ['banned'] = false },
	{ ['name'] = "buffalo2", ['banned'] = false },
	{ ['name'] = "buffalo3", ['banned'] = false },
	{ ['name'] = "carbonizzare", ['banned'] = false },
	{ ['name'] = "comet2", ['banned'] = false },
	{ ['name'] = "comet3", ['banned'] = false },
	{ ['name'] = "comet5", ['banned'] = false },
	{ ['name'] = "coquette", ['banned'] = false },
	{ ['name'] = "elegy", ['banned'] = false },
	{ ['name'] = "elegy2", ['banned'] = false },
	{ ['name'] = "feltzer2", ['banned'] = false },
	{ ['name'] = "furoregt", ['banned'] = false },
	{ ['name'] = "fusilade", ['banned'] = false },
	{ ['name'] = "futo", ['banned'] = false },
	{ ['name'] = "jester", ['banned'] = false },
	{ ['name'] = "khamelion", ['banned'] = false },
	{ ['name'] = "massacro", ['banned'] = false },
	{ ['name'] = "massacro2", ['banned'] = false },
	{ ['name'] = "ninef", ['banned'] = false},
	{ ['name'] = "ninef2", ['banned'] = false },
	{ ['name'] = "omnis", ['banned'] = false },
	{ ['name'] = "pariah", ['banned'] = false },
	{ ['name'] = "penumbra", ['banned'] = false },
	{ ['name'] = "raiden", ['banned'] = false },
	{ ['name'] = "rapidgt", ['banned'] = false },
	{ ['name'] = "rapidgt2",['banned'] = false },
	{ ['name'] = "ruston", ['banned'] = false },
	{ ['name'] = "schafter3", ['banned'] = false },
	{ ['name'] = "schafter4", ['banned'] = false },
	{ ['name'] = "schafter5", ['banned'] = false },
	{ ['name'] = "schafter6", ['banned'] = false },
	{ ['name'] = "schwarzer", ['banned'] = false },
	{ ['name'] = "sentinel3", ['banned'] = false },
	{ ['name'] = "seven70", ['banned'] = false },
	{ ['name'] = "specter", ['banned'] = false },
	{ ['name'] = "specter2", ['banned'] = false },
	{ ['name'] = "streiter", ['banned'] = false },
	{ ['name'] = "sultan", ['banned'] = false },
	{ ['name'] = "surano", ['banned'] = false },
	{ ['name'] = "tampa2", ['banned'] = false },
	{ ['name'] = "tropos",  ['banned'] = false },
	{ ['name'] = "verlierer2", ['banned'] = false },
	{ ['name'] = "btype", ['banned'] = false },
	{ ['name'] = "btype2", ['banned'] = false },
	{ ['name'] = "btype3", ['banned'] = false },
	{ ['name'] = "casco", ['banned'] = false },
	{ ['name'] = "cheetah", ['banned'] = false },
	{ ['name'] = "coquette2", ['banned'] = false },
	{ ['name'] = "feltzer3", ['banned'] = false },
	{ ['name'] = "gt500", ['banned'] = false },
	{ ['name'] = "infernus2", ['banned'] = false },
	{ ['name'] = "jb700", ['banned'] = false },
	{ ['name'] = "mamba", ['banned'] = false },
	{ ['name'] = "manana", ['banned'] = false },
	{ ['name'] = "monroe", ['banned'] = false },
	{ ['name'] = "peyote", ['banned'] = false },
	{ ['name'] = "pigalle", ['banned'] = false },
	{ ['name'] = "rapidgt3", ['banned'] = false },
	{ ['name'] = "retinue", ['banned'] = false },
	{ ['name'] = "stinger", ['banned'] = false },
	{ ['name'] = "stingergt", ['banned'] = false },
	{ ['name'] = "torero", ['banned'] = false },
	{ ['name'] = "tornado", ['banned'] = false },
	{ ['name'] = "tornado2", ['banned'] = false },
	{ ['name'] = "tornado5", ['banned'] = false },
	{ ['name'] = "tornado6", ['banned'] = false },
	{ ['name'] = "turismo2", ['banned'] = false },
	{ ['name'] = "ztype", ['banned'] = false },
	{ ['name'] = "adder", ['banned'] = false },
	{ ['name'] = "autarch", ['banned'] = false },
	{ ['name'] = "banshee2", ['banned'] = false },
	{ ['name'] = "bullet",  ['banned'] = false },
	{ ['name'] = "cheetah2", ['banned'] = false },
	{ ['name'] = "entityxf", ['banned'] = false },
	{ ['name'] = "fmj", ['banned'] = false },
	{ ['name'] = "gp1", ['banned'] = false },
	{ ['name'] = "infernus", ['banned'] = false },
	{ ['name'] = "nero", ['banned'] = false },
	{ ['name'] = "nero2", ['banned'] = false },
	{ ['name'] = "osiris", ['banned'] = false },
	{ ['name'] = "penetrator", ['banned'] = false },
	{ ['name'] = "pfister811", ['banned'] = false },
	{ ['name'] = "reaper", ['banned'] = false },
	{ ['name'] = "sc1", ['banned'] = false },
	{ ['name'] = "sultanrs", ['banned'] = false },
	{ ['name'] = "t20", ['banned'] = false },
	{ ['name'] = "tempesta", ['banned'] = false },
	{ ['name'] = "turismor", ['banned'] = false },
	{ ['name'] = "tyrus", ['banned'] = false },
	{ ['name'] = "vacca", ['banned'] = false },
	{ ['name'] = "visione", ['banned'] = false },
	{ ['name'] = "voltic", ['banned'] = false },
	{ ['name'] = "zentorno", ['banned'] = false },
	{ ['name'] = "sadler", ['banned'] = false },
	{ ['name'] = "bison", ['banned'] = false },
	{ ['name'] = "bison2", ['banned'] = false },
	{ ['name'] = "bobcatxl", ['banned'] = false },
	{ ['name'] = "burrito", ['banned'] = false },
	{ ['name'] = "burrito2", ['banned'] = false },
	{ ['name'] = "burrito3", ['banned'] = false },
	{ ['name'] = "burrito4", ['banned'] = false },
	{ ['name'] = "minivan", ['banned'] = false },
	{ ['name'] = "minivan2", ['banned'] = false },
	{ ['name'] = "paradise", ['banned'] = false },
	{ ['name'] = "pony", ['banned'] = false },
	{ ['name'] = "pony2", ['banned'] = false },
	{ ['name'] = "rumpo", ['banned'] = false },
	{ ['name'] = "rumpo2", ['banned'] = false },
	{ ['name'] = "rumpo3", ['banned'] = false },
	{ ['name'] = "speedo", ['banned'] = false },
	{ ['name'] = "surfer", ['banned'] = false },
	{ ['name'] = "youga", ['banned'] = false },
	{ ['name'] = "youga2", ['banned'] = false },
	{ ['name'] = "rebel", ['banned'] = false },
	{ ['name'] = "tractor2", ['banned'] = false },
	{ ['name'] = "huntley", ['banned'] = false },
	{ ['name'] = "landstalker", ['banned'] = false },
	{ ['name'] = "mesa", ['banned'] = false },
	{ ['name'] = "patriot", ['banned'] = false },
	{ ['name'] = "radi", ['banned'] = false },
	{ ['name'] = "rocoto", ['banned'] = false },
	{ ['name'] = "tyrant", ['banned'] = false },
	{ ['name'] = "entity2", ['banned'] = false },
	{ ['name'] = "cheburek", ['banned'] = false },
	{ ['name'] = "hotring", ['banned'] = false },
	{ ['name'] = "jester3", ['banned'] = false },
	{ ['name'] = "flashgt", ['banned'] = false },
	{ ['name'] = "ellie", ['banned'] = false },
	{ ['name'] = "michelli", ['banned'] = false },
	{ ['name'] = "fagaloa", ['banned'] = false },
	{ ['name'] = "dominator2", ['banned'] = false },
	{ ['name'] = "dominator3", ['banned'] = false },
	{ ['name'] = "issi3", ['banned'] = false },
	{ ['name'] = "taipan", ['banned'] = false },
	{ ['name'] = "gb200", ['banned'] = false },
	{ ['name'] = "stretch", ['banned'] = false },
	{ ['name'] = "guardian", ['banned'] = false },
	{ ['name'] = "kamacho", ['banned'] = false },
	{ ['name'] = "neon", ['banned'] = false },
	{ ['name'] = "cyclone", ['banned'] = false },
	{ ['name'] = "italigtb", ['banned'] = false },
	{ ['name'] = "italigtb2", ['banned'] = false },
	{ ['name'] = "vagner", ['banned'] = false },
	{ ['name'] = "xa21", ['banned'] = false },
	{ ['name'] = "tezeract", ['banned'] = false },
	{ ['name'] = "prototipo", ['banned'] = false },
	{ ['name'] = "patriot2", ['banned'] = false },
	{ ['name'] = "stafford", ['banned'] = false },
	{ ['name'] = "swinger", ['banned'] = false },
	{ ['name'] = "clique", ['banned'] = false },
	{ ['name'] = "deveste", ['banned'] = false },
	{ ['name'] = "deviant", ['banned'] = false },
	{ ['name'] = "impaler", ['banned'] = false },
	{ ['name'] = "italigto", ['banned'] = false },
	{ ['name'] = "schlagen", ['banned'] = false },
	{ ['name'] = "toros", ['banned'] = false },
	{ ['name'] = "tulip", ['banned'] = false },
	{ ['name'] = "vamos", ['banned'] = false },
	{ ['name'] = "freecrawler", ['banned'] = false },	
	{ ['name'] = "fugitive", ['banned'] = false },
	{ ['name'] = "le7b", ['banned'] = false },
	{ ['name'] = "lurcher", ['banned'] = false },
	{ ['name'] = "lynx", ['banned'] = false },
	{ ['name'] = "raptor", ['banned'] = false },
	{ ['name'] = "sheava", ['banned'] = false },
	{ ['name'] = "z190", ['banned'] = false },
	{ ['name'] = "akuma", ['banned'] = false },
	{ ['name'] = "avarus", ['banned'] = false },
	{ ['name'] = "bagger", ['banned'] = false },
	{ ['name'] = "bati", ['banned'] = false },
	{ ['name'] = "bati2", ['banned'] = false },
	{ ['name'] = "bf400", ['banned'] = false },
	{ ['name'] = "carbonrs", ['banned'] = false },
	{ ['name'] = "chimera", ['banned'] = false },
	{ ['name'] = "cliffhanger", ['banned'] = false },
	{ ['name'] = "daemon", ['banned'] = false },
	{ ['name'] = "daemon2", ['banned'] = false },
	{ ['name'] = "defiler", ['banned'] = false },
	{ ['name'] = "diablous", ['banned'] = false },
	{ ['name'] = "diablous2", ['banned'] = false },
	{ ['name'] = "double",  ['banned'] = false },
	{ ['name'] = "enduro", ['banned'] = false },
	{ ['name'] = "esskey", ['banned'] = false },
	{ ['name'] = "faggio",  ['banned'] = false },
	{ ['name'] = "faggio2", ['banned'] = false },
	{ ['name'] = "faggio3", ['banned'] = false },
	{ ['name'] = "fcr", ['banned'] = false },
	{ ['name'] = "fcr2", ['banned'] = false },
	{ ['name'] = "gargoyle", ['banned'] = false },
	{ ['name'] = "hakuchou", ['banned'] = false },
	{ ['name'] = "hakuchou2", ['banned'] = false },
	{ ['name'] = "hexer", ['banned'] = false },
	{ ['name'] = "innovation", ['banned'] = false },
	{ ['name'] = "lectro", ['banned'] = false },
	{ ['name'] = "manchez", ['banned'] = false },
	{ ['name'] = "nemesis", ['banned'] = false },
	{ ['name'] = "nightblade", ['banned'] = false },
	{ ['name'] = "pcj", ['banned'] = false },
	{ ['name'] = "ruffian", ['banned'] = false },
	{ ['name'] = "sanchez", ['banned'] = false },
	{ ['name'] = "sanchez2", ['banned'] = false },
	{ ['name'] = "sanctus", ['banned'] = false },
	{ ['name'] = "sovereign", ['banned'] = false },
	{ ['name'] = "thrust", ['banned'] = false },
	{ ['name'] = "vader", ['banned'] = false },
	{ ['name'] = "vindicator", ['banned'] = false },
	{ ['name'] = "vortex", ['banned'] = false },
	{ ['name'] = "wolfsbane", ['banned'] = false },
	{ ['name'] = "zombiea", ['banned'] = false },
	{ ['name'] = "zombieb", ['banned'] = false },
	{ ['name'] = "blazer", ['banned'] = false },
	{ ['name'] = "blazer4", ['banned'] = false },
	{ ['name'] = "shotaro", ['banned'] = false },
	{ ['name'] = "ratbike", ['banned'] = false },
	{ ['name'] = "pbus", ['banned'] = true },
	{ ['name'] = "mule4", ['banned'] = false },
	{ ['name'] = "rallytruck", ['banned'] = false },
	{ ['name'] = "riot", ['banned'] = true },
	{ ['name'] = "coach", ['banned'] = true },
	{ ['name'] = "bus", ['banned'] = true },
	{ ['name'] = "flatbed", ['banned'] = true },
	{ ['name'] = "towtruck", ['banned'] = true },
	{ ['name'] = "towtruck2", ['banned'] = true },
	{ ['name'] = "ratloader", ['banned'] = true },
	{ ['name'] = "ratloader2", ['banned'] = false },
	{ ['name'] = "rubble", ['banned'] = true },
	{ ['name'] = "taxi", ['banned'] = true },
	{ ['name'] = "boxville4", ['banned'] = false },
	{ ['name'] = "trash2", ['banned'] = false },
	{ ['name'] = "tiptruck", ['banned'] = false },
	{ ['name'] = "scorcher", ['banned'] = true },
	{ ['name'] = "tribike", ['banned'] = true },
	{ ['name'] = "tribike2", ['banned'] = true },
	{ ['name'] = "tribike3", ['banned'] = true },
	{ ['name'] = "fixter", ['banned'] = true },
	{ ['name'] = "cruiser", ['banned'] = true },
	{ ['name'] = "bmx", ['banned'] = true },
	{ ['name'] = "dinghy", ['banned'] = true },
	{ ['name'] = "jetmax", ['banned'] = true },
	{ ['name'] = "marquis", ['banned'] = true },
	{ ['name'] = "seashark3", ['banned'] = true },
	{ ['name'] = "speeder", ['banned'] = true },
	{ ['name'] = "speeder2", ['banned'] = true },
	{ ['name'] = "squalo", ['banned'] = true },
	{ ['name'] = "suntrap", ['banned'] = true },
	{ ['name'] = "toro", ['banned'] = true },
	{ ['name'] = "toro2", ['banned'] = true },
	{ ['name'] = "tropic", ['banned'] = true },
	{ ['name'] = "tropic2", ['banned'] = true },
	{ ['name'] = "phantom", ['banned'] = true },
	{ ['name'] = "packer", ['banned'] = true },
	{ ['name'] = "supervolito", ['banned'] = true },
	{ ['name'] = "supervolito2", ['banned'] = true },
	{ ['name'] = "seasparrow", ['banned'] = true },
	{ ['name'] = "cuban800", ['banned'] = true },
	{ ['name'] = "mammatus", ['banned'] = true },
	{ ['name'] = "vestra", ['banned'] = true },
	{ ['name'] = "velum2", ['banned'] = true },
	{ ['name'] = "buzzard2", ['banned'] = true },
	{ ['name'] = "frogger", ['banned'] = true },
	{ ['name'] = "maverick", ['banned'] = true },
	{ ['name'] = "tanker2", ['banned'] = true },
	{ ['name'] = "armytanker", ['banned'] = true },
	{ ['name'] = "tvtrailer", ['banned'] = true },
	{ ['name'] = "trailerlogs", ['banned'] = true },
	{ ['name'] = "sprinter1", ['banned'] = true },
	{ ['name'] = "gm5303", ['banned'] = false },
	{ ['name'] = "zendrack", ['banned'] = true },
	{ ['name'] = "tr4", ['banned'] = true },
	{ ['name'] = "sw4", ['banned'] = true },
}
-----------------------------------------------------------------------------------------------------------------------------------------
-- VEHLIST
-----------------------------------------------------------------------------------------------------------------------------------------
function tvRP.vehList(radius)
    local ped = PlayerPedId()
    local veh = GetVehiclePedIsUsing(ped)
    if not IsPedInAnyVehicle(ped) then
        veh = tvRP.getNearestVehicle(radius)
    end
    if IsEntityAVehicle(veh) then
        local lock = GetVehicleDoorLockStatus(veh)
        local trunk = GetVehicleDoorAngleRatio(v,5)
        local x,y,z = table.unpack(GetEntityCoords(ped))
        for k,v in pairs(vehList) do
            if GetHashKey(v.name) == GetEntityModel(veh) then 
                if v.name then
                    local tuning = { GetNumVehicleMods(veh,13),GetNumVehicleMods(veh,12),GetNumVehicleMods(veh,15),GetNumVehicleMods(veh,11),GetNumVehicleMods(veh,16) }
                    return veh,VehToNet(veh),GetVehicleNumberPlateText(veh),v.name,lock,v.banned,trunk,GetDisplayNameFromVehicleModel(v.name),GetStreetNameFromHashKey(GetStreetNameAtCoord(x,y,z)),tuning
                end
            end
        end
    end
end